server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.addr}
        namespace: ${nacos.namespace}
    loadbalancer:
      ribbon:
          enabled: false
      nacos:
        enabled: true

nacos:
  addr: 127.0.0.1:8848
  namespace: icoffee-cloud



